version: '3.9'

services:

  web:
    image: konstant81/fastapi_test
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
      
  db:
    container_name: db
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi_db
    restart: always
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
